spring.config.import=optional:file:.env[.properties]

spring.application.name=backend-app-dat-xe

spring.datasource.url=${DB_POSTGRESQL_URI}
spring.datasource.username=${DB_POSTGRESQL_USERNAME}
spring.datasource.password=${DB_POSTGRESQL_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.uri=${DB_REDIS_URI}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

openweathermap.api.url=https://api.openweathermap.org/data/2.5/weather
openweathermap.api.key=${OVM_KEY}

tomtom.api.url=https://api.tomtom.com
tomtom.api.key=${TOMTOM_API_KEY}

mapbox.api.navigation.url=https://api.mapbox.com
mapbox.api.navigation.key=${MAPBOX_PUBLIC_TOKEN}